{
 "openapi": "3.0.3",
 "info": {
  "title": "IVCAP",
  "description": "\n**IVCAP** is for **service providers** to **offer** analytics **services**\nand for **consumers** to **order** customised **products** produced by said services.\n\n### Typical Workflow\n\n1. Obtain an token from the ID Providers listed in the document returned\nby [/1/authinfo.yaml](/1/authinfo.yaml). The token needs to be added\nas a bearer token via the\n<code>Authorization</code> header to every request to this service.\n1. <a href=\"#get-/1/services\">List</a> all availa[...]",
  "version": "0.48"
 },
 "servers": [
  {
   "url": "https://develop.ivcap.net",
   "description": "This endpoint hosts all the IVCAP services."
  }
 ],
 "paths": {
  "/1/artifacts": {
   "get": {
    "tags": [
     "artifact"
    ],
    "summary": "list artifact",
    "description": "list artifacts",
    "operationId": "artifact#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "artifact"
    ],
    "summary": "upload artifact",
    "description": "Upload content and create a artifacts.",
    "operationId": "artifact#upload",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/artifacts/{id}": {
   "get": {
    "tags": [
     "artifact"
    ],
    "summary": "read artifact",
    "description": "Show artifacts by ID",
    "operationId": "artifact#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/aspects": {
   "get": {
    "tags": [
     "aspect"
    ],
    "summary": "list aspect",
    "description": "Return a list of aspect aspects.",
    "operationId": "aspect#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "aspect"
    ],
    "summary": "create aspect",
    "description": "Attach new aspect to an entity.",
    "operationId": "aspect#create",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "aspect"
    ],
    "summary": "update aspect",
    "description": "A convenience method which will create a new aspect, but will also\n\t\tretract a potentially existing aspect for the same entity with the same schema.",
    "operationId": "aspect#update",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/aspects/{id}": {
   "delete": {
    "tags": [
     "aspect"
    ],
    "summary": "retract aspect",
    "description": "Retract a previously created statement.",
    "operationId": "aspect#retract",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "aspect"
    ],
    "summary": "read aspect",
    "description": "Show aspects by ID",
    "operationId": "aspect#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/dashboards": {
   "get": {
    "tags": [
     "dashboard"
    ],
    "summary": "list dashboard",
    "description": "list dashboards",
    "operationId": "dashboard#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/metadata": {
   "get": {
    "tags": [
     "metadata"
    ],
    "summary": "list metadata",
    "description": "Return a list of metadata records.",
    "operationId": "metadata#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "metadata"
    ],
    "summary": "add metadata",
    "description": "Attach new metadata to an entity.",
    "operationId": "metadata#add",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/metadata/{id}": {
   "delete": {
    "tags": [
     "metadata"
    ],
    "summary": "revoke metadata",
    "description": "Retract a previously created statement.",
    "operationId": "metadata#revoke",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "metadata"
    ],
    "summary": "read metadata",
    "description": "Show metadata by ID",
    "operationId": "metadata#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "metadata"
    ],
    "summary": "update_record metadata",
    "description": "Revoke this record and create a new one with the information provided.\n\t\t\tFor any field not provided, the value from the current record is used.",
    "operationId": "metadata#update_record",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/openapi/openapi3.json": {
   "get": {
    "tags": [
     "openapi"
    ],
    "summary": "Download /public/openapi3.json",
    "description": "JSON document containing the API swagger definition",
    "operationId": "openapi#/1/openapi/openapi3.json"
   }
  },
  "/1/orders": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "list order",
    "description": "list orders",
    "operationId": "order#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "order"
    ],
    "summary": "create order",
    "description": "Create a new orders and return its status.",
    "operationId": "order#create",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/orders/{id}": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "read order",
    "description": "Show orders by ID",
    "operationId": "order#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/orders/{orderID}/logs": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "logs order",
    "description": "download order logs",
    "operationId": "order#logs",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/orders/{orderID}/metadata": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "metadata order",
    "description": "list metadata created by an order",
    "operationId": "order#metadata",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/orders/{orderID}/products": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "products order",
    "description": "list products created by an order",
    "operationId": "order#products",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/orders/{orderID}/top": {
   "get": {
    "tags": [
     "order"
    ],
    "summary": "top order",
    "description": "top order resources",
    "operationId": "order#top",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/packages/list": {
   "get": {
    "tags": [
     "package"
    ],
    "summary": "list package",
    "description": "list ivcap service's docker images under account",
    "operationId": "package#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/packages/remove": {
   "delete": {
    "tags": [
     "package"
    ],
    "summary": "remove package",
    "description": "remove ivcap service's docker image",
    "operationId": "package#remove",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/project": {
   "get": {
    "tags": [
     "project"
    ],
    "summary": "List User's Projects",
    "description": "list project",
    "operationId": "project#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "project"
    ],
    "summary": "Create a Project",
    "description": "Create a new project and return its status.",
    "operationId": "project#CreateProject",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/project/default": {
   "get": {
    "tags": [
     "project"
    ],
    "summary": "Get User's Default Project",
    "description": "Retrieves the user's current default project",
    "operationId": "project#DefaultProject",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "project"
    ],
    "summary": "Set User's Default Project",
    "description": "Sets the default project of a user.",
    "operationId": "project#SetDefaultProject",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/project/{id}": {
   "delete": {
    "tags": [
     "project"
    ],
    "summary": "Delete a Project",
    "description": "Delete an existing project.",
    "operationId": "project#delete",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "project"
    ],
    "summary": "Get Project Information",
    "description": "Show project by ID",
    "operationId": "project#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/project/{project_urn}/account": {
   "get": {
    "tags": [
     "project"
    ],
    "summary": "Get Project's Billing Account",
    "description": "Retrieves the project's billing account urn",
    "operationId": "project#ProjectAccount",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "project"
    ],
    "summary": "Set Project's Billing Account",
    "description": "Sets the billing account of a project",
    "operationId": "project#SetProjectAccount",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/project/{project_urn}/memberships/{user_urn}": {
   "delete": {
    "tags": [
     "project"
    ],
    "summary": "Remove User Membership",
    "description": "Remove a user from a project.",
    "operationId": "project#RemoveMembership",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "project"
    ],
    "summary": "Add or Update User Membership",
    "description": "Adds or Updates the roles of a user in a project.",
    "operationId": "project#UpdateMembership",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/project/{urn}": {
   "put": {
    "tags": [
     "project"
    ],
    "summary": "Set Project Information",
    "description": "Sets the metadata of a project.",
    "operationId": "project#SetProjectInformation",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/project/{urn}/members": {
   "get": {
    "tags": [
     "project"
    ],
    "summary": "List Project Members",
    "description": "Lists the current members of a project.",
    "operationId": "project#ListProjectMembers",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/queues": {
   "get": {
    "tags": [
     "queue"
    ],
    "summary": "list queue",
    "description": "list queues",
    "operationId": "queue#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "queue"
    ],
    "summary": "create queue",
    "description": "Create a new queues and return its status.",
    "operationId": "queue#create",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/queues/{id}": {
   "delete": {
    "tags": [
     "queue"
    ],
    "summary": "delete queue",
    "description": "Delete an existing queues.",
    "operationId": "queue#delete",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "queue"
    ],
    "summary": "read queue",
    "description": "Show queues by ID",
    "operationId": "queue#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/queues/{id}/messages": {
   "get": {
    "tags": [
     "queue"
    ],
    "summary": "dequeue queue",
    "description": "Read a message from a specific queues.",
    "operationId": "queue#dequeue",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "queue"
    ],
    "summary": "enqueue queue",
    "description": "Send a message to a specific queues.",
    "operationId": "queue#enqueue",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/search": {
   "post": {
    "tags": [
     "search"
    ],
    "summary": "search search",
    "description": "Execute query provided in body and return a list of search result.",
    "operationId": "search#search",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/secrets": {
   "get": {
    "tags": [
     "secret"
    ],
    "summary": "get secret",
    "description": "Get a secrets",
    "operationId": "secret#get",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "secret"
    ],
    "summary": "set secret",
    "description": "Set a secrets",
    "operationId": "secret#set",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/secrets/list": {
   "get": {
    "tags": [
     "secret"
    ],
    "summary": "list secret",
    "description": "list secrets under account",
    "operationId": "secret#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/services": {
   "get": {
    "tags": [
     "servicex"
    ],
    "summary": "list servicex",
    "description": "list services",
    "operationId": "servicex#list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "servicex"
    ],
    "summary": "create_service servicex",
    "description": "Create a new services and return its status.",
    "operationId": "servicex#create_service",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services/{id}": {
   "delete": {
    "tags": [
     "servicex"
    ],
    "summary": "delete servicex",
    "description": "Delete an existing services.",
    "operationId": "servicex#delete",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "servicex"
    ],
    "summary": "read servicex",
    "description": "Show services by ID",
    "operationId": "servicex#read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "servicex"
    ],
    "summary": "update servicex",
    "description": "Update an existing services and return its status.",
    "operationId": "servicex#update",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services2": {
   "get": {
    "tags": [
     "service"
    ],
    "summary": "service-list service",
    "description": "list services",
    "operationId": "service#service-list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "service"
    ],
    "summary": "service-create service",
    "description": "Create a new service and return its status.",
    "operationId": "service#service-create",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services2/{id}": {
   "delete": {
    "tags": [
     "service"
    ],
    "summary": "service-delete service",
    "description": "Delete an existing service.",
    "operationId": "service#service-delete",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "service"
    ],
    "summary": "service-read service",
    "description": "Show service by ID",
    "operationId": "service#service-read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "service"
    ],
    "summary": "service-update service",
    "description": "Update an existing service and return its status.",
    "operationId": "service#service-update",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services2/{service_id}/jobs": {
   "get": {
    "tags": [
     "service"
    ],
    "summary": "job-list service",
    "description": "list jobs for a specific service",
    "operationId": "service#job-list",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "service"
    ],
    "summary": "job-create service",
    "description": "Create a job in the context of a specific service.",
    "operationId": "service#job-create",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services2/{service_id}/jobs/{id}": {
   "get": {
    "tags": [
     "service"
    ],
    "summary": "job-read service",
    "description": "show the status of a job within the context of a service",
    "operationId": "service#job-read",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:read"
      ]
     }
    ]
   }
  },
  "/1/services2/{service_id}/jobs/{job_id}/events": {
   "get": {
    "tags": [
     "service"
    ],
    "summary": "job-events service",
    "description": "Return a stream of job releated events.",
    "operationId": "service#job-events",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  },
  "/1/services2/{service_id}/jobs/{job_id}/output": {
   "get": {
    "tags": [
     "service"
    ],
    "summary": "job-output service",
    "description": "Return the result of a job.",
    "operationId": "service#job-output",
    "security": [
     {
      "jwt_header_Authorization": [
       "consumer:write"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "jwt_header_Authorization": {
    "type": "http",
    "description": "Secures endpoint by requiring a valid JWT token",
    "scheme": "bearer"
   }
  }
 },
 "tags": [
  {
   "name": "openapi",
   "description": "The openapi service serves the OpenAPI definition."
  },
  {
   "name": "aspect",
   "description": "Manages the life cycle of aspect(s) attached to some entity."
  },
  {
   "name": "queue",
   "description": "Manage the life cycle of a queue."
  },
  {
   "name": "search",
   "description": "Provides a search capability across the entire system."
  },
  {
   "name": "service",
   "description": "Manage the life cycle of a service offered on IVCAP."
  },
  {
   "name": "artifact",
   "description": "Manage the life cycle of an artifact stored by this deployment."
  },
  {
   "name": "dashboard",
   "description": "list dashboards"
  },
  {
   "name": "metadata",
   "description": "Manages the life cycle of metadata attached to an entity."
  },
  {
   "name": "order",
   "description": "Manage the life cycle of an order for CRE services."
  },
  {
   "name": "package",
   "description": "Manage the life cycle of a service package."
  },
  {
   "name": "project",
   "description": "Create, Join, Manage Projects"
  },
  {
   "name": "secret",
   "description": "List, set or get secrets"
  },
  {
   "name": "servicex",
   "description": "Manage the life cycle of a service offered on the CRE marketplace."
  }
 ]
}